// <auto-generated />
using I4DAB_LAB2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace I4DAB_LAB2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20191105130315_TestMig")]
    partial class TestMig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("I4DAB_LAB2.Dish", b =>
                {
                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Dishes");
                });

            modelBuilder.Entity("I4DAB_LAB2.Guest", b =>
                {
                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("I4DAB_LAB2.Person", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("People");
                });

            modelBuilder.Entity("I4DAB_LAB2.Restaurant", b =>
                {
                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Address");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("I4DAB_LAB2.Review", b =>
                {
                    b.Property<int>("Stars")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RestaurantAddress")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Stars");

                    b.HasIndex("RestaurantAddress");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("I4DAB_LAB2.Table", b =>
                {
                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("I4DAB_LAB2.Waiter", b =>
                {
                    b.Property<int>("Salery")
                        .HasColumnType("int");

                    b.ToTable("Waiters");
                });

            modelBuilder.Entity("I4DAB_LAB2.Review", b =>
                {
                    b.HasOne("I4DAB_LAB2.Restaurant", "Restaurant")
                        .WithMany("Reviews")
                        .HasForeignKey("RestaurantAddress");
                });
#pragma warning restore 612, 618
        }
    }
}
